project:
  type: website
  output-dir: docs
  resources:
    - easa-exam/**
    - CNAME
  preview:
    port: 4200
    browser: false
    navigate: true

website:
  title: "dronelab.dev"
  open-graph:
    image: holybro-x500.png
    title: "DroneLab - Coding Autonomous Drones in Baby Steps."
    description: "On this blog, dronelab.dev, I'm exploring machine learning by teaching a drone how to fly itself. I break things down into small steps and share what I discover along the way."
    site-name: dronelab.dev
    image-alt: "DroneLab - Coding Autonomous Drones in Baby Steps."
    image-width: 1280
    image-height: 720
  google-analytics: "G-J790G06FED"
  site-url: https://dronelab.dev
  favicon: favicon.ico
  description: "DroneLab - Coding Autonomous Drones in Baby Steps."
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pors
      - icon: twitter
        href: https://twitter.com/pors
      - icon: rss
        href: index.xml
  twitter-card:
    title: "DroneLab - Coding Autonomous Drones in Baby Steps."
    description: "On this blog, dronelab.dev, I'm exploring machine learning by teaching a drone how to fly itself. I break things down into small steps and share what I discover along the way. "
    site: "@pors"
    creator: "@pors"
    card-style: summary_large_image
    image: holybro-x500.png
    image-alt: "DroneLab - Coding Autonomous Drones in Baby Steps."
format:
  html:
    theme:
      - flatly
    css: styles.css
    title-block-style: none

execute:
  cache: true
