project:
  type: website
  output-dir: docs
  resources:
    - easa-exam/**   

website:
  title: "dronelab.dev"
  open-graph: true
  google-analytics: "G-J790G06FED"
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - flatly
    css: styles.css
    title-block-style: none

execute:
  cache: true
